<?php
return array (
  'site_title' => 'EduaskCMS测试站',
  'site_keywords' => '',
  'site_description' => '',
  'site_copyright' => '&copy;xxxx 版权所有',
  'site_code' => '',
  'corp_title' => '公司名称',
  'tel' => '公司电话',
  'email' => '公司邮箱',
  'address' => '公司地址',
  'icp' => '蜀ICP备xxxxxx号',
  'public_qrcode' => '',
  'is_verify' => '1',
  'default_verify' => '1',
  'list_count' => '15',
  'admin_list_count' => '15',
  'is_admin_cache' => '0',
  'is_feedback_list' => '1',
  'is_menu_position' => '0',
  'is_trace' => '1',
  'is_debug' => '1',
  'use_picture_model' => '["Album"]',
  'thumb_method' => '3',
  'thumb_width' => '400',
  'thumb_height' => '300',
  'default_image' => '',
  'is_water' => '0',
  'water_model' => '',
  'water_type' => 'text',
  'water_location' => '9',
  'water_image' => '',
  'water_image_opacity' => '100',
  'water_text' => '',
  'water_text_size' => '20',
  'water_text_color' => '#ffffff',
  'email_host' => 'smtp.163.com',
  'email_from' => '',
  'email_password' => '',
  'email_fromname' => 'EduaskCMS',
  'sms_keyid' => '',
  'sms_keysecret' => '',
  'yt_appid' => '',
  'yt_secretid' => '',
  'yt_secretkey' => '',
)
?>